name: yu_ni_image_widget_example
description: Example app for yu_ni_image_widget.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  yu_ni_image_widget:
    path: ../
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.3.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
