name: yu_ni_image_widget
description: A high-performance Flutter image widget with separated display and cache, classified memory management, and viewport priority scheduling.
version: 0.1.0
homepage: https://github.com/lurongshuang/yu_ni_image_widget
repository: https://github.com/lurongshuang/yu_ni_image_widget
issue_tracker: https://github.com/lurongshuang/yu_ni_image_widget/issues

topics:
  - image
  - cache
  - performance
  - scheduler
  - widget

platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  octo_image: ^2.1.0
  yuni_widget: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
